using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Generator;

namespace Generator
{
    //To add a new word into the vocabulary, just add it in to any of the lists below
    //To add a new type of word, just create a new instance of Choice by copying the syntax below
    //Any of the existing types of word may be deleted any time
    //The Noun class implements the IPluralize interface
    //The Word class does not implement the IPluralize interface
    public static class Vocabulary
    {
        //The food vocabulary was contributed by Nora Reed. See this page for more info:
        //https://medium.com/@NoraReed/some-word-lists-for-bot-making-4b8d68d4740
        public static Choice Food = new Choice(new List<IGenerate>
        {
            new Word("roasted nuts"),
            new Word("curried nuts"),
            new Word("roasted chestnuts"),
            new Word("toasted pumpkin seeds"),
            new Word("toasted sunflower seeds"),
            new Word("popcorn"),
            new Word("Spanish style marinated olives"),
            new Word("sour cream dip"),
            new Word("clam dip"),
            new Word("shrimp dip"),
            new Word("red onion dip"),
            new Word("guacamole"),
            new Word("Texas caviar"),
            new Word("hot chorizo and cheese dip"),
            new Word("hot crab dip"),
            new Word("baked artichoke dip"),
            new Word("seven-layer dip"),
            new Word("hummus"),
            new Word("baba ghanoush"),
            new Word("eggplant caviar"),
            new Word("garlic cheese spread"),
            new Word("marinated mozzarella"),
            new Word("fried mozzarella spread"),
            new Word("nachos"),
            new Word("quesadillas"),
            new Word("honey yogurt dip"),
            new Word("crudites"),
            new Word("crispy potato skins"),
            new Word("buffalo chicken wings"),
            new Word("lemon rosemary chicken"),
            new Word("chicken fingers"),
            new Word("beef satay"),
            new Word("cocktail meatballs"),
            new Word("salami rolls"),
            new Word("smoked turkey and arugula rolls"),
            new Word("beef and scallion rolls"),
            new Word("baked honey shrimp"),
            new Word("cajun popcorn shrimp"),
            new Word("beer-batter shrimp"),
            new Word("coconut shrimp"),
            new Word("smoked salmon rolls"),
            new Word("ham biscuits"),
            new Word("mushroom triangles"),
            new Word("spinach and feta triangles"),
            new Word("turnovers"),
            new Word("cocktail tartlets"),
            new Word("miniature quiches"),
            new Word("stuffed choux puffs"),
            new Word("cheese puffs"),
            new Word("pigs in a blanket"),
            new Word("egg rolls"),
            new Word("summer rolls"),
            new Word("pot stickers"),
            new Word("fried wontons"),
            new Word("bagel chips"),
            new Word("pita chips"),
            new Word("soda crackers"),
            new Word("potato chips"),
            new Word("root vegetable chips"),
            new Word("tortilla chips"),
            new Word("drip coffee"),
            new Word("steeped coffee"),
            new Word("turkish coffee"),
            new Word("jamaican coffee"),
            new Word("irish coffee"),
            new Word("cafe diablo"),
            new Word("spiced tea"),
            new Word("sweet southern iced tea"),
            new Word("hot cocoa"),
            new Word("egg cream"),
            new Word("broth on the rocks"),
            new Word("citrus juice medley"),
            new Word("pineapple grapefruit juice"),
            new Word("raspberry or blackberry shrub"),
            new Word("cranberry juice"),
            new Word("hot cranberry juice"),
            new Word("mulled cider"),
            new Word("celery-apple-watermelon splash"),
            new Word("pineapple juice"),
            new Word("tropical juice"),
            new Word("fruit soda"),
            new Word("ice cream soda"),
            new Word("milk shake"),
            new Word("tropical smoothie"),
            new Word("mango lassi"),
            new Word("fruit kefir"),
            new Word("pink lemonade"),
            new Word("watermelon punch"),
            new Word("pineapple punch"),
            new Word("fruit punch"),
            new Word("Cocomoka"),
            new Word("sugar syrup"),
            new Word("fruit syrup"),
            new Word("spiced syrup"),
            new Word("casserole"),
            new Word("tetrazzini"),
            new Word("crab strata"),
            new Word("pork shoulder"),
            new Word("seafood stew"),
            new Word("hearty meat ragu"),
            new Word("hamburger pie"),
            new Word("shepard's pie"),
            new Word("chicken potpie"),
            new Word("enchiladas"),
            new Word("chop suey"),
            new Word("chow mein"),
            new Word("sweet and sour pork"),
            new Word("curry"),
            new Word("hot chicken salad"),
            new Word("ham loaf"),
            new Word("fish loaf"),
            new Word("corned beef "),
            new Word("quiche lorraine"),
            new Word("quiche"),
            new Word("leek tart"),
            new Word("cheese custard"),
            new Word("fondue"),
            new Word("welsh rarebit"),
            new Word("shrimp wiggle"),
            new Word("cornmeal mush"),
            new Word("polenta"),
            new Word("fried polenta"),
            new Word("grits"),
            new Word("shrimp and grits"),
            new Word("posole"),
            new Word("tamales"),
            new Word("millet cakes"),
            new Word("granola"),
            new Word("muesli"),
            new Word("quinoa pilaf"),
            new Word("baked white rice"),
            new Word("rice pilaf"),
            new Word("spanish rice"),
            new Word("chicken jambalaya"),
            new Word("fried rice"),
            new Word("risotto"),
            new Word("tabbouleh"),
            new Word("pasta"),
            new Word("egg noodles"),
            new Word("macaroni and cheese"),
            new Word("pasta primavera"),
            new Word("fettuccine alfredo"),
            new Word("spaghetti carbonara"),
            new Word("lo mein"),
            new Word("pad thai"),
            new Word("szechuan noodles"),
            new Word("moon-viewing noodles"),
            new Word("dumplings"),
            new Word("gnocchi"),
            new Word("spatzle"),
            new Word("pastitsio"),
            new Word("cheese filling"),
            new Word("ravioli"),
            new Word("tortellini"),
            new Word("cannelloni"),
            new Word("lasagne"),
            new Word("lasagne bolognese"),
            new Word("vareniki"),
            new Word("pierogi"),
            new Word("wontons"),
            new Word("vegetable wontons"),
            new Word("stuffed artichokes"),
            new Word("fried artichokes"),
            new Word("roasted asparagus"),
            new Word("green beans"),
            new Word("boiled beans"),
            new Word("refried beans"),
            new Word("vegetarian chili"),
            new Word("caribbean red bean stew"),
            new Word("baked beans"),
            new Word("tuscan beans"),
            new Word("mashed fava beans"),
            new Word("red beans and rice"),
            new Word("brazilian black beans"),
            new Word("steamed broccoli"),
            new Word("deep-fried broccoli"),
            new Word("stir-fry"),
            new Word("creamed cabbage"),
            new Word("stuffed cabbage rolls"),
            new Word("braised red cabbage"),
            new Word("sauerkraut"),
            new Word("carrot puree"),
            new Word("carrots vichy"),
            new Word("braised carrots"),
            new Word("glazed carrots"),
            new Word("roasted carrots"),
            new Word("steamed cauliflower"),
            new Word("mashed cauliflower"),
            new Word("scalloped cauliflower"),
            new Word("celery"),
            new Word("corn on the cob"),
            new Word("creamed corn"),
            new Word("corn pudding"),
            new Word("fresh corn fritters"),
            new Word("fried eggplant"),
            new Word("eggplant parmigiana"),
            new Word("moussaka"),
            new Word("roasted garlic"),
            new Word("grilled mushrooms"),
            new Word("sauteed mushrooms"),
            new Word("creamed mushrooms"),
            new Word("mushroom ragout"),
            new Word("fried okra"),
            new Word("steamed onions"),
            new Word("grilled sweet onions"),
            new Word("sauteed onions"),
            new Word("caramelized onions"),
            new Word("onion rings"),
            new Word("deep-fried parsley"),
            new Word("french parsnips"),
            new Word("roasted peppers"),
            new Word("stuffed bell peppers"),
            new Word("deep-fried plantains"),
            new Word("tostones"),
            new Word("mashed potatoes"),
            new Word("creamed potatoes"),
            new Word("scalloped potatoe"),
            new Word("au gratin potatoes"),
            new Word("baked potatoes"),
            new Word("twice-baked potatoes"),
            new Word("hash browns"),
            new Word("potato pancakes"),
            new Word("latkes"),
            new Word("french fries"),
            new Word("potato croquettes"),
            new Word("boiled spinach"),
            new Word("creamed spinach"),
            new Word("wilted spinach"),
            new Word("saag paneer"),
            new Word("deep-fried zucchini"),
            new Word("baked winter squas"),
            new Word("taro cakes"),
            new Word("stewed tomatoes"),
            new Word("fried green tomatoes"),
            new Word("turnip puree"),
            new Word("moo shu tempeh"),
            new Word("szechuan-style tempeh"),
            new Word("dinner loaf"),
            new Word("seitan"),
            new Word("soft-boiled eggs"),
            new Word("hard-boiled eggs"),
            new Word("coddled eggs"),
            new Word("creamed eggs au gratin"),
            new Word("curried eggs"),
            new Word("deviled eggs"),
            new Word("scotch eggs"),
            new Word("fried eggs"),
            new Word("eggs in a basket"),
            new Word("huevos rancheros"),
            new Word("poached eggs"),
            new Word("eggs florentine"),
            new Word("eggs benedict"),
            new Word("scrambled eggs"),
            new Word("matzo brei"),
            new Word("baked egg"),
            new Word("eggs in a nest"),
            new Word("french omelet"),
            new Word("omelet"),
            new Word("frittata"),
            new Word("hangtown fry"),
            new Word("denver omelet"),
            new Word("potato omelet"),
            new Word("tortilla espanola"),
            new Word("spinach souffle"),
            new Word("mushroom souffle"),
            new Word("meat glaze"),
            new Word("dashi"),
            new Word("egg drop soup"),
            new Word("avgolemono"),
            new Word("stracciatella"),
            new Word("garlic soup with eggs"),
            new Word("sopa de ajo"),
            new Word("miso"),
            new Word("chicken noodle soup"),
            new Word("matzo ball soup"),
            new Word("wonton soup"),
            new Word("minestrone"),
            new Word("borscht"),
            new Word("bean soup"),
            new Word("white bean soup"),
            new Word("black bean soup"),
            new Word("lentil soup"),
            new Word("split pea soup"),
            new Word("mock turtle soup"),
            new Word("scotch broth"),
            new Word("caldo verde"),
            new Word("pepper pot"),
            new Word("charleston crab"),
            new Word("lobster bisque"),
            new Word("cream of mussel soup"),
            new Word("bisque"),
            new Word("gumbo"),
            new Word("bouillabaisse"),
            new Word("new england clam chowder"),
            new Word("manhattan clam chowder"),
            new Word("corn chowder"),
            new Word("cream of broccoli soup"),
            new Word("chestnut soup"),
            new Word("milk toast"),
            new Word("new year's soup"),
            new Word("gazpacho"),
            new Word("soup"),
            new Word("beef stew"),
            new Word("dried fruit compote"),
            new Word("poached fruit"),
            new Word("apple rings"),
            new Word("honey apples"),
            new Word("sauteed apples"),
            new Word("applesauce"),
            new Word("baked apples"),
            new Word("honey-grilled bananas"),
            new Word("strawberries romanoff"),
            new Word("blueberry syrup"),
            new Word("syrup"),
            new Word("cranberry sauce"),
            new Word("poached cherries"),
            new Word("citrus salad"),
            new Word("kumquat compote"),
            new Word("stuffed dates"),
            new Word("baked figs"),
            new Word("poached pears"),
            new Word("stuffed pears"),
            new Word("walnut butter"),
            new Word("honey butter"),
            new Word("cream cheese"),
            new Word("waffles"),
            new Word("BLT"),
            new Word("club sandwich"),
            new Word("twin sandwich"),
            new Word("reuben"),
            new Word("croque monsieur"),
            new Word("croque madame sandwich"),
            new Word("monte cristo"),
            new Word("cuban sandwich"),
            new Word("panini"),
            new Word("muffuletta"),
            new Word("cheese toast"),
            new Word("tuna melt"),
            new Word("pizza"),
            new Word("lox"),
            new Word("submarine sandwich"),
            new Word("po-boy"),
            new Word("hot dog"),
            new Word("corn dog"),
            new Word("tea sandwiches"),
            new Word("gyro"),
            new Word("falafel"),
            new Word("taco"),
            new Word("fajitas"),
            new Word("pizza margherita"),
            new Word("calzone"),
            new Word("stromboli"),
            new Word("green salad"),
            new Word("green salad"),
            new Word("caesar salad"),
            new Word("greek salad"),
            new Word("spinach salad"),
            new Word("wilted greens"),
            new Word("coleslaw"),
            new Word("hot slaw"),
            new Word("chef's salad"),
            new Word("cobb salad"),
            new Word("salade nicoise"),
            new Word("vinaigrette"),
            new Word("taco salad"),
            new Word("chicken salad"),
            new Word("tuna salad"),
            new Word("seafood salad"),
            new Word("marinated cucumbers"),
            new Word("potato salad"),
            new Word("waldorf salad"),
            new Word("chickpea salad"),
            new Word("pasta salad"),
            new Word("tomato aspic"),
            new Word("broiled oysters"),
            new Word("grilled oysters"),
            new Word("fried breaded oysters"),
            new Word("steamed mussels"),
            new Word("buttered baked mussels"),
            new Word("grilled mussels"),
            new Word("steamed clams"),
            new Word("broiled clams"),
            new Word("clambake"),
            new Word("poached scallops"),
            new Word("crab cakes"),
            new Word("steamed lobster"),
            new Word("lobster thermidor"),
            new Word("lobster newburg"),
            new Word("shrimp scampi"),
            new Word("deep-fried shrimp"),
            new Word("tempura"),
            new Word("stuffed squid"),
            new Word("whelk salad"),
            new Word("turtle soup"),
            new Word("snails"),
            new Word("deep-fried frog legs"),
            new Word("chili sauce"),
            new Word("catsup"),
            new Word("pickled ginger"),
            new Word("pickled peppers"),
            new Word("grape jelly"),
            new Word("gooseberry jam"),
            new Word("plum jam"),
            new Word("baked apple butter"),
            new Word("preserves"),
            new Word("marmalade"),
            new Word("truffles"),
            new Word("truffle cups"),
            new Word("chocolate bark"),
            new Word("peanut butter cup"),
            new Word("coconut cake"),
            new Word("chocolate clusters"),
            new Word("fudge cockaigne"),
            new Word("peanut butter fudge"),
            new Word("cream caramels"),
            new Word("caramel corn"),
            new Word("fondant"),
            new Word("peppermint wafers"),
            new Word("nougat"),
            new Word("divinity"),
            new Word("marshmallow"),
            new Word("vanilla taffy"),
            new Word("saltwater taffy"),
            new Word("english toffee"),
            new Word("buttercrunch"),
            new Word("butterscotch"),
            new Word("coffee drops"),
            new Word("lollipop"),
            new Word("rock candy"),
            new Word("pralines"),
            new Word("marzipan"),
            new Word("bourbon balls"),
            new Word("heavenly hash"),
            new Word("candied apples"),
            new Word("caramel apples"),
            new Word("candied citrus peel"),
            new Word("candied ginger"),
            new Word("ice cream pie"),
            new Word("ice cream"),
            new Word("ice milk"),
            new Word("gelato"),
            new Word("frozen yogurt"),
            new Word("sorbet"),
            new Word("blackberry sorbet"),
            new Word("blueberry sorbet"),
            new Word("strawberry sorbet"),
            new Word("mango sorbet"),
            new Word("peach sorbet"),
            new Word("lemon sorbet"),
            new Word("lime sorbet"),
            new Word("orange sorbet"),
            new Word("lemon sherbet"),
            new Word("lime sherbet"),
            new Word("cranberry sherbet"),
            new Word("ice pops"),
            new Word("berry granita"),
            new Word("espresso granita"),
            new Word("caffe latte granita"),
            new Word("granita"),
            new Word("coffee parfait"),
            new Word("hazelnut semifreddo"),
            new Word("semifreddo"),
            new Word("souffle"),
            new Word("baked alaska"),
            new Word("hot lemon sauce"),
            new Word("custard sauce"),
            new Word("hot fudge sauce"),
            new Word("mocha sauce"),
            new Word("caramel sauce"),
            new Word("caramel syrup"),
            new Word("butterscotch sauce"),
            new Word("rum sauce"),
            new Word("marshmallow sauce"),
            new Word("sour cream sauce"),
            new Word("raspberry coulis"),
            new Word("decorative icing"),
            new Word("creamy decorating icing"),
            new Word("royal icing"),
            new Word("caramel frosting"),
            new Word("buttercream"),
            new Word("cream cheese frosting"),
            new Word("chocolate satin frosting"),
            new Word("translucent sugar glaze"),
            new Word("brownies"),
            new Word("blondies"),
            new Word("cheesecake"),
            new Word("toffee bars"),
            new Word("nut bars"),
            new Word("energy bars"),
            new Word("lemon bars"),
            new Word("gingersnaps"),
            new Word("peanut butter cookies"),
            new Word("oatmeal raisin cookies"),
            new Word("oatmeal chocolate chip cookies"),
            new Word("snickerdoodles"),
            new Word("ginger thins"),
            new Word("orange marmalade drops"),
            new Word("butterscotch nut cookies"),
            new Word("macaroons"),
            new Word("meringue kisses"),
            new Word("sand tarts"),
            new Word("tarts"),
            new Word("gingerbread men"),
            new Word("viennese crescents"),
            new Word("letter cookies"),
            new Word("mandelplattchen"),
            new Word("biscotti"),
            new Word("cinnamon stars"),
            new Word("scotch shortbread"),
            new Word("shortbread"),
            new Word("rugelach"),
            new Word("ice cream cones"),
            new Word("fortune cookies"),
            new Word("gingerbread house"),
            new Word("ginger sauce"),
            new Word("roasted red pepper sauce"),
            new Word("burgundy sauce"),
            new Word("mole"),
            new Word("mustard"),
            new Word("ghee"),
            new Word("butter"),
            new Word("black butter"),
            new Word("lemon butter"),
            new Word("walnut butter"),
            new Word("anchovy butter"),
            new Word("mint sauce"),
            new Word("raisin sauce"),
            new Word("chimichurri"),
            new Word("hot sauce"),
            new Word("tzatziki"),
            new Word("pesto"),
            new Word("peanut sauce"),
            new Word("wasabi"),
            new Word("vinaigrette"),
            new Word("horseradish"),
            new Word("avocado dressing"),
            new Word("blue cheese vinaigrette"),
            new Word("anchovy dressing"),
            new Word("celery seed dressing"),
            new Word("parmesan vinaigrette"),
            new Word("roasted red pepper dressing"),
            new Word("tangerine shallot dressing"),
            new Word("apricot dressing"),
            new Word("mayonnaise"),
            new Word("souffleed mayonnaise"),
            new Word("watercress mayonnaise"),
            new Word("brown sugar glaze"),
            new Word("cranberry glaze"),
            new Word("marmalade glaze"),
            new Word("mustard glaze"),
            new Word("pineapple glaze"),
            new Word("milk bread"),
            new Word("cinnamon raisin bread"),
            new Word("cheese bread"),
            new Word("herb bread"),
            new Word("buttermilk potato bread"),
            new Word("challah"),
            new Word("french bread"),
            new Word("sourdough bread"),
            new Word("tuscan loaf"),
            new Word("naan"),
            new Word("sopapillas"),
            new Word("hot cross buns"),
            new Word("cheese rolls"),
            new Word("sticky buns"),
            new Word("bear claws"),
            new Word("whole wheat rolls"),
            new Word("rye rolls"),
            new Word("oat rolls"),
            new Word("brioche"),
            new Word("brioche au chocolat"),
            new Word("croissants"),
            new Word("english muffins"),
            new Word("crumpets"),
            new Word("bagels"),
            new Word("pretzels"),
            new Word("bread sticks "),
            new Word("yeasted coffee cake"),
            new Word("kneaded filled coffee cake"),
            new Word("kugelhopf"),
            new Word("raspberry danish pinwheels"),
            new Word("orange bread"),
            new Word("banana bread"),
            new Word("pumpkin bread"),
            new Word("carrot nut bread"),
            new Word("beer bread"),
            new Word("irish soda bread"),
            new Word("poppy seed loaf"),
            new Word("brown bread"),
            new Word("bishop's bread"),
            new Word("crumb cake"),
            new Word("corn bread"),
            new Word("hush puppies"),
            new Word("muffins"),
            new Word("sour cream muffins"),
            new Word("lemon poppy seed muffins"),
            new Word("pumpkin or sweet potato muffins"),
            new Word("blueberry muffins"),
            new Word("herb or roasted garlic muffins"),
            new Word("whole wheat muffins"),
            new Word("bran muffins"),
            new Word("cheese muffins"),
            new Word("apple walnut muffins"),
            new Word("banana nut muffins"),
            new Word("popovers"),
            new Word("cheese popovers"),
            new Word("yorkshire pudding"),
            new Word("cornmeal biscuits"),
            new Word("buttermilk biscuits"),
            new Word("shortcake"),
            new Word("scones"),
            new Word("lemon scones"),
            new Word("chocolate chip orange scones"),
            new Word("melba cheese rounds"),
            new Word("crostini"),
            new Word("honey-butter toast"),
            new Word("orange toast"),
            new Word("angel cake"),
            new Word("sponge cake"),
            new Word("daffodil cake"),
            new Word("tres leches cake"),
            new Word("genoise"),
            new Word("white cake"),
            new Word("marble cake"),
            new Word("german chocolate cake"),
            new Word("velvet spice cake"),
            new Word("brown sugar spice cake"),
            new Word("burnt sugar cake"),
            new Word("applesauce cake"),
            new Word("rombauer jam cake"),
            new Word("oatmeal cake"),
            new Word("blitzkuchen"),
            new Word("texas sheet cake"),
            new Word("mississippi mud cake"),
            new Word("rum cake"),
            new Word("orange almond cake"),
            new Word("apple cake"),
            new Word("carrot cake"),
            new Word("gingerbread"),
            new Word("Guy Fawkes day cake"),
            new Word("honey cake"),
            new Word("fruitcake cockaigne"),
            new Word("fruitcake"),
            new Word("torte"),
            new Word("jelly roll"),
            new Word("chiffon cake sheet"),
            new Word("angel cake sheet"),
            new Word("chocolate cupcakes"),
            new Word("caramel cupcakes"),
            new Word("petit fours"),
            new Word("madeleines"),
            new Word("ladyfingers"),
            new Word("meringue"),
            new Word("chocolate cheesecake"),
            new Word("pumpkin cheesecake"),
            new Word("lemon syrup"),
            new Word("apple strudel"),
            new Word("baklava"),
            new Word("apple pie"),
            new Word("apple tartlets"),
            new Word("peach pie"),
            new Word("rhubarb pie"),
            new Word("strawberry rhubarb pie"),
            new Word("concord grape pie"),
            new Word("raisin pie"),
            new Word("fresh fruit tart"),
            new Word("pecan pie"),
            new Word("bourbon pie"),
            new Word("shoofly pie"),
            new Word("chess pie"),
            new Word("jefferson davis pie"),
            new Word("buttermilk chess pie"),
            new Word("lemon chess pie"),
            new Word("chess tarts"),
            new Word("maple syrup pie"),
            new Word("peanut butter pie"),
            new Word("custard pie"),
            new Word("chocolate glazed custard pie"),
            new Word("vanilla cream pie"),
            new Word("chocolate cream pie"),
            new Word("banana cream pie"),
            new Word("butterscotch cream pie"),
            new Word("coconut cream pie"),
            new Word("lemon meringue pie"),
            new Word("lemon tart"),
            new Word("raspberry bavarian pie"),
            new Word("black bottom pie"),
            new Word("pumpkin chiffon pie"),
            new Word("pineapple upside-down cake"),
            new Word("apple dumplings"),
            new Word("pear turnovers"),
            new Word("linzertorte"),
            new Word("dessert pizza"),
            new Word("pancakes"),
            new Word("buttermilk pancakes"),
            new Word("silver dollar pancakes"),
            new Word("flapjacks"),
            new Word("oatmeal pancakes"),
            new Word("waffles"),
            new Word("buttermilk waffles"),
            new Word("french toast"),
            new Word("crepes"),
            new Word("crepes suzette"),
            new Word("crepes with caramelized apples"),
            new Word("blueberry blintzes"),
            new Word("cake doughnuts"),
            new Word("jelly doughnuts"),
            new Word("crullers"),
            new Word("beignets"),
            new Word("tempura"),
            new Word("fritters"),
            new Word("croquettes"),
            new Word("stuffing"),
            new Word("chicken farce"),
            new Word("sauteed rabbit"),
            new Word("fricassee "),
            new Word("rabbit ala mode"),
            new Word("chili"),
            new Word("burgers"),
            new Word("boar chops"),
            new Word("braised bear"),
            new Word("buffalo rib roast"),
            new Word("buffalo burgers"),
            new Word("chicken-fried steak"),
            new Word("beef stroganoff"),
            new Word("sukiyaki"),
            new Word("pot roast"),
            new Word("beef stew"),
            new Word("sweet and sour brisket"),
            new Word("smoked brisket"),
            new Word("chuck roast"),
            new Word("short ribs"),
            new Word("corned beef"),
            new Word("roast leg of lamb"),
            new Word("stuffed butterflied leg of lamb"),
            new Word("rack of lamb"),
            new Word("sauteed lamb chops"),
            new Word("kebabs"),
            new Word("braised shoulder of lamb"),
            new Word("irish stew"),
            new Word("pork roast"),
            new Word("pulled pork"),
            new Word("roast suckling pig"),
            new Word("pork adobo"),
            new Word("grilled pork tenderloin"),
            new Word("pork chops"),
            new Word("spareribs"),
            new Word("baked ham "),
            new Word("broiled ham steak"),
            new Word("bacon"),
            new Word("hamburgers"),
            new Word("cheeseburgers"),
            new Word("patty melt"),
            new Word("sloppy joe"),
            new Word("meat loaf"),
            new Word("swedish meatballs"),
            new Word("chili con carne"),
            new Word("country sausage"),
            new Word("liver and onions"),
            new Word("pickled beef tongue"),
            new Word("oxtail stew"),
            new Word("poached chicken or turkey"),
            new Word("roast chicken"),
            new Word("broiled chicken"),
            new Word("jamaican jerk chicken"),
            new Word("tandoori chicken"),
            new Word("fried chicken"),
            new Word("coq au vin"),
            new Word("sesame chicken"),
            new Word("chicken and rice"),
            new Word("arroz con pollo"),
            new Word("chicken piccata"),
            new Word("stir-fried garlic chicken"),
            new Word("roast turkey"),
            new Word("turned roast turkey"),
            new Word("roast brined turkey"),
            new Word("chutney turkey burgers"),
            new Word("roast duck"),
            new Word("crispy roast duck"),
            new Word("goose confit"),
            new Word("pheasant"),
            new Word("grouse"),
            new Word("partridge"),
            new Word("wild rice pilau"),
            new Word("poached fish"),
            new Word("fish fillets"),
            new Word("sardine toast"),
            new Word("kedgeree"),
            new Word("rice pudding"),
            new Word("cheese curds"),
            new Word("fish fry"),
            new Word("fish and chips"),
            new Word("Cornish pasties"),
            new Word("carne adovada"),
            new Word("fish boil"),
            new Word("bratwurst"),
            new Word("cranberry wine"),
            new Word("beer cheese soup"),
            new Word("brandy old fashioned"),
            new Word("rhubarb pie"),
            new Word("mango kulfi"),
            new Word("Bedfordshire clanger"),
            new Word("spotted dick"),
            new Word("head cheese"),
            new Word("fairy bread"),
            new Word("sliders"),
            new Word("po-boy"),
            new Word("Marmite sandwiches"),
            new Word("filet mignon"),
            new Word("cube steak"),
            new Word("tiramisu"),
        });

        public static Choice Animal = new Choice(new List<IGenerate>
        {
            new Noun("bat"),
            new Noun("bear"),
            new Noun("bird"),
            new Noun("bull"),
            new Noun("cat"),
            new Noun("cobra"),
            new Noun("cow"),
            new Noun("crab"),
            new Noun("dog"),
            new Noun("donkey"),
            new Noun("fox", "foxes"),
            new Noun("frog"),
            new Noun("hare"),
            new Noun("horse"),
            new Noun("kitten"),
            new Noun("monkey"),
            new Noun("owl"),
            new Noun("mole"),
            new Noun("mouse", "mice"),
            new Noun("pig"),
            new Noun("pigeon"),
            new Noun("rabbit"),
            new Noun("rat"),
            new Noun("sheep", "sheep"),
            new Noun("snake"),
            new Noun("toad"),
            new Noun("tiger"),
            new Noun("vulture"),
            new Noun("wolf", "wolves"),
        });

        public static Choice Occupation = new Choice(new List<IGenerate>
        {
            new Noun("baker"),
            new Noun("boat captain"),
            new Noun("butcher"),
            new Noun("charlatan"),
            new Noun("cook"),
            new Noun("farmer"),
            new Noun("fisherman", "fishermen"),
            new Noun("hero"),
            //new Noun("knight"),
            //new Noun("orphan"),
            new Noun("parson"),
            new Noun("prankster"),
            new Noun("priest"),
            new Noun("sailor"),
            new Noun("soldier"),
        });

        public static Choice GovtOfficial = new Choice(new List<IGenerate>
        {
            new Noun("a senator"),
            new Noun("a committee chair"),
            new Noun("a member of the the joint chiefs of staff"),
            new Noun("an associate justice of the Supreme Court"),
            new Noun("a member of congress"),
            new Noun("an ambassador"),
            new Noun("a congressional page"),
            new Noun("a cabinet secretary"),
            new Noun("a European head of state"),
            new Noun("an FBI agent"),
            new Noun("a secret service agent"),
            new Noun("a CIA spook"),
            new Noun("a presidential aide"),
            new Noun("a white house staffer"),
            new Noun("a senate staffer"),
            new Noun("a deputy secretary"),
            new Noun("the President"),
            new Noun("the Chief Justice of the Supreme Court"),
            new Noun("the Secretary of Minefields and Machetes"),
            new Noun("the Secretary of the Exterior"),
            new Noun("the Secretary of Mediation and Meditation"),
            new Noun("the Secretary of Dirty Tricks and Hissy Fits"),
            new Noun("the Secretary of Constipation and Consternation"),
            new Noun("the Senate Parliamentarian"),
            new Noun("the Architect of the Capitol"),
            new Noun("the Speaker"),
            new Noun("the Vice Chairman of the Senate Republican Caucus"),
            new Noun("the Chairman of the Congressional Black Caucus"),
            new Noun("the Senate Sergeant at Arms"),
            new Word("a professor of semiotics at Georgetown University"),
            new Word("the Archbishop of Baltimore"),
            new Word("the Mayor of Washington"),
            new Word("an at-large member of the city council"),
            new Word("a security guard"),
        });

        public static Choice GeographicFeature = new Choice(new List<IGenerate>
        {
            new Noun("bay"),
            new Noun("cave"),
            new Noun("cavern"),
            new Noun("creek"),
            new Noun("forest"),
            new Noun("lake"),
            new Noun("meadow"),
            new Noun("pit"),
            new Noun("pond"),
            new Noun("river"),
            new Noun("town"),
            new Noun("trap"),
            new Noun("wood"),
        });

        public static Choice Dwelling = new Choice(new List<IGenerate>
        {
            new Noun("city", "cities"),
            new Noun("dwelling"),
            new Noun("house"),
            new Noun("hovel"),
            new Noun("hut"),
            new Noun("mansion"),
            new Noun("palace"),
            new Noun("village"),
            new Noun("workshop"),
        });

        public static Choice Place = Dwelling + GeographicFeature;

        public static Choice TimeOfDay = new Choice(new List<IGenerate>
        {
            new Word("dawn"),
            new Word("daybreak"),
            new Word("dusk"),
            new Word("lunchtime"),
            new Word("mid day"),
            new Word("the morning"),
            new Word("night"),
            new Word("nightfall"),
            new Word("noontime"),
            new Word("sunrise"),
            new Word("sunset"),
            new Word("the afternoon"),
            new Word("the evening"),
        });

        public static Choice Meal = new Choice(new List<IGenerate> {
            new Word("breakfast"),
            new Word("lunch"),
            new Word("brunch"),
            new Word("dinner"),
            new Word("afternoon tea"),
            new Word("supper"),
            new Word("late night snacks"),
            new Word("pizza"),
            new Word("ice cream"),

        });

        public static Choice IntransitiveVerb = new Choice(new List<IGenerate>
        {
            new Word("climbs"),
            new Word("cries"),
            new Word("dies"),
            new Word("eats"),
            new Word("flees"),
            new Word("gripes"),
            new Word("runs"),
            new Word("screams"),
            new Word("talks"),
            new Word("writhes"),
            new Word("dances"),
            new Word("shivers"),
            new Word("trembles"),
            new Word("wails"),
            new Word("whispers"),

        });

        public static Choice TransitiveVerb = new Choice(new List<IGenerate>
        {
            new Word("cheers"),
            new Word("dreads"),
            new Word("fears"),
            new Word("fights"),
            new Word("flees"),
            new Word("slays"),
            new Word("fights with"),
            new Word("kisses"),
            new Word("laughs at"),
            new Word("plays with"),
            new Word("smiles at"),
            new Word("sneers at"),
            new Word("embraces"),

        });

        public static Choice MotionVerb = new Choice(new List<IGenerate>
        {
            new Word("crawls"),
            new Word("flies"),
            new Word("runs"),
            new Word("strides"),
            new Word("strolls"),
            new Word("trots"),
            new Word("walks"),
            new Word("gallops"),
            new Word("hurries"),
            new Word("marches"),
            new Word("parades"),
            new Word("rushes"),
            new Word("scuttles"),

        });

        //This color list is an edited version of WikiPedia's big color list that starts here:
        //https://en.wikipedia.org/wiki/List_of_colors:_A-F
        public static Choice ColorAdjective = new Choice(new List<IGenerate>
        {
            new Word("acid green"),
            new Word("aero blue"),
            new Word("african violet"),
            new Word("air force blue"),
            new Word("air superiority blue"),
            new Word("alabama crimson"),
            new Word("alabaster"),
            new Word("alice blue"),
            new Word("alizarin crimson"),
            new Word("alloy orange"),
            new Word("almond"),
            new Word("amaranth"),
            new Word("amaranth deep purple"),
            new Word("amaranth pink"),
            new Word("amaranth purple"),
            new Word("amaranth red"),
            new Word("amber"),
            new Word("american blue"),
            new Word("american brown"),
            new Word("american gold"),
            new Word("american green"),
            new Word("american orange"),
            new Word("american pink"),
            new Word("american purple"),
            new Word("american red"),
            new Word("american rose"),
            new Word("american silver"),
            new Word("american violet"),
            new Word("american yellow"),
            new Word("amethyst"),
            new Word("android green"),
            new Word("anti-flash white"),
            new Word("antique brass"),
            new Word("antique bronze"),
            new Word("antique fuchsia"),
            new Word("antique ruby"),
            new Word("antique white"),
            new Word("apple green"),
            new Word("apricot"),
            new Word("aqua"),
            new Word("aquamarine"),
            new Word("arctic lime"),
            new Word("army green"),
            new Word("arsenic"),
            new Word("artichoke"),
            new Word("arylide yellow"),
            new Word("ash gray"),
            new Word("asparagus"),
            new Word("ateneo blue"),
            new Word("atomic tangerine"),
            new Word("auburn"),
            new Word("avocado"),
            new Word("aztec gold"),
            new Word("azure"),
            new Word("azure mist"),
            new Word("azureish white"),
            new Word("baby blue"),
            new Word("baby blue eyes"),
            new Word("baby pink"),
            new Word("baby powder"),
            new Word("baker-miller pink"),
            new Word("ball blue"),
            new Word("banana yellow"),
            new Word("bangladesh green"),
            new Word("barbie pink"),
            new Word("barn red"),
            new Word("battery charged blue"),
            new Word("battleship grey"),
            new Word("beau blue"),
            new Word("begonia"),
            new Word("beige"),
            new Word("b'dazzled blue"),
            new Word("bisque"),
            new Word("bistre brown"),
            new Word("bitter lemon"),
            new Word("bitter lime"),
            new Word("black"),
            new Word("black bean"),
            new Word("black chocolate"),
            new Word("black coffee"),
            new Word("black coral"),
            new Word("black leather jacket"),
            new Word("black olive"),
            new Word("blackberry"),
            new Word("black shadows"),
            new Word("blanched almond"),
            new Word("blast-off bronze"),
            new Word("bleu de france"),
            new Word("blizzard blue"),
            new Word("blond"),
            new Word("blood orange"),
            new Word("blood red"),
            new Word("blue"),
            new Word("blue bell"),
            new Word("blue bolt"),
            new Word("blue-gray"),
            new Word("blue-green"),
            new Word("blue jeans"),
            new Word("blue lagoon"),
            new Word("blue-magenta violet"),
            new Word("blue sapphire"),
            new Word("blue-violet"),
            new Word("blue yonder"),
            new Word("blueberry"),
            new Word("bluebonnet"),
            new Word("blush"),
            new Word("bondi blue"),
            new Word("bone"),
            new Word("bottle green"),
            new Word("boysenberry"),
            new Word("brandeis blue"),
            new Word("brass"),
            new Word("brick red"),
            new Word("bright cerulean"),
            new Word("bright gray"),
            new Word("bright green"),
            new Word("bright lavender"),
            new Word("bright lilac"),
            new Word("bright maroon"),
            new Word("bright navy blue"),
            new Word("bright pink"),
            new Word("bright turquoise"),
            new Word("bright ube"),
            new Word("bright yellow"),
            new Word("brilliant azure"),
            new Word("brilliant lavender"),
            new Word("brilliant rose"),
            new Word("brink pink"),
            new Word("british racing green"),
            new Word("bronze"),
            new Word("bronze yellow"),
            new Word("brown"),
            new Word("brown sugar"),
            new Word("brown chocolate"),
            new Word("brown coffee"),
            new Word("brown yellow"),
            new Word("brunswick green"),
            new Word("bubble gum pink"),
            new Word("bud green"),
            new Word("buff"),
            new Word("bulgarian rose"),
            new Word("burgundy"),
            new Word("burlywood"),
            new Word("burnished brown"),
            new Word("burnt orange"),
            new Word("burnt sienna"),
            new Word("burnt umber"),
            new Word("button blue"),
            new Word("cadet blue"),
            new Word("cadet grey"),
            new Word("cadmium blue"),
            new Word("cadmium green"),
            new Word("cadmium orange"),
            new Word("cadmium purple"),
            new Word("cadmium red"),
            new Word("cadmium yellow"),
            new Word("cadmium violet"),
            new Word("café au lait"),
            new Word("café noir"),
            new Word("camel"),
            new Word("cameo pink"),
            new Word("camouflage green"),
            new Word("canary"),
            new Word("canary yellow"),
            new Word("candy apple red"),
            new Word("candy pink"),
            new Word("caramel"),
            new Word("cardinal red"),
            new Word("caribbean green"),
            new Word("carmine"),
            new Word("carmine pink"),
            new Word("carmine red"),
            new Word("carnation pink"),
            new Word("carnelian"),
            new Word("carolina blue"),
            new Word("carrot orange"),
            new Word("castleton green"),
            new Word("catalina blue"),
            new Word("cedar chest"),
            new Word("ceil"),
            new Word("celadon blue"),
            new Word("celadon green"),
            new Word("celestial blue"),
            new Word("cerise"),
            new Word("cerise pink"),
            new Word("cerulean"),
            new Word("cerulean blue"),
            new Word("cerulean frost"),
            new Word("chamoisee"),
            new Word("champagne"),
            new Word("champagne pink"),
            new Word("charcoal"),
            new Word("charleston green"),
            new Word("charm"),
            new Word("charm pink"),
            new Word("chartreuse"),
            new Word("cherry"),
            new Word("cherry blossom pink"),
            new Word("chestnut"),
            new Word("china pink"),
            new Word("china rose"),
            new Word("chinese black"),
            new Word("chinese blue"),
            new Word("chinese bronze"),
            new Word("chinese brown"),
            new Word("chinese green"),
            new Word("chinese gold"),
            new Word("chinese orange"),
            new Word("chinese pink"),
            new Word("chinese purple"),
            new Word("chinese red"),
            new Word("chinese red"),
            new Word("chinese silver"),
            new Word("chinese violet"),
            new Word("chinese white"),
            new Word("chinese yellow"),
            new Word("chlorophyll green"),
            new Word("chocolate"),
            new Word("christmas blue"),
            new Word("christmas blue"),
            new Word("christmas brown"),
            new Word("christmas green"),
            new Word("christmas gold"),
            new Word("christmas orange"),
            new Word("christmas pink"),
            new Word("christmas purple"),
            new Word("christmas red"),
            new Word("christmas red"),
            new Word("christmas silver"),
            new Word("christmas yellow"),
            new Word("chrome yellow"),
            new Word("cinnabar"),
            new Word("cinnamon"),
            new Word("cinnamon satin"),
            new Word("citrine"),
            new Word("citrine brown"),
            new Word("citron"),
            new Word("claret"),
            new Word("classic rose"),
            new Word("cobalt blue"),
            new Word("cocoa brown"),
            new Word("coconut"),
            new Word("coffee"),
            new Word("columbia blue"),
            new Word("congo pink"),
            new Word("cool black"),
            new Word("cool grey"),
            new Word("copper"),
            new Word("copper penny"),
            new Word("copper red"),
            new Word("copper rose"),
            new Word("coquelicot"),
            new Word("coral"),
            new Word("coral pink"),
            new Word("coral red"),
            new Word("coral reef"),
            new Word("cordovan"),
            new Word("corn"),
            new Word("cornell red"),
            new Word("cornflower blue"),
            new Word("cosmic cobalt"),
            new Word("cosmic latte"),
            new Word("coyote brown"),
            new Word("cotton candy"),
            new Word("cream"),
            new Word("crimson"),
            new Word("crimson glory"),
            new Word("crimson red"),
            new Word("cultured"),
            new Word("cyan"),
            new Word("cyan azure"),
            new Word("cyan-blue azure"),
            new Word("cyan cobalt blue"),
            new Word("cyan cornflower blue"),
            new Word("cyber grape"),
            new Word("cyber yellow"),
            new Word("cyclamen"),
            new Word("daffodil"),
            new Word("dandelion"),
            new Word("dark blue"),
            new Word("dark blue-gray"),
            new Word("dark bronze"),
            new Word("dark brown"),
            new Word("dark brown-tangelo"),
            new Word("dark byzantium"),
            new Word("dark candy apple red"),
            new Word("dark cerulean"),
            new Word("dark charcoal"),
            new Word("dark chestnut"),
            new Word("dark chocolate"),
            new Word("dark cornflower blue"),
            new Word("dark coral"),
            new Word("dark cyan"),
            new Word("dark electric blue"),
            new Word("dark goldenrod"),
            new Word("dark gray"),
            new Word("dark green"),
            new Word("dark gunmetal"),
            new Word("dark imperial blue"),
            new Word("dark imperial blue"),
            new Word("dark jungle green"),
            new Word("dark khaki"),
            new Word("dark lava"),
            new Word("dark lavender"),
            new Word("dark lemon lime"),
            new Word("dark liver"),
            new Word("dark magenta"),
            new Word("dark medium gray"),
            new Word("dark midnight blue"),
            new Word("dark moss green"),
            new Word("dark olive green"),
            new Word("dark orange"),
            new Word("dark orchid"),
            new Word("dark pastel blue"),
            new Word("dark pastel green"),
            new Word("dark pastel purple"),
            new Word("dark pastel red"),
            new Word("dark pink"),
            new Word("dark powder blue"),
            new Word("dark puce"),
            new Word("dark purple"),
            new Word("dark raspberry"),
            new Word("dark red"),
            new Word("dark salmon"),
            new Word("dark scarlet"),
            new Word("dark sea green"),
            new Word("dark sienna"),
            new Word("dark sky blue"),
            new Word("dark slate blue"),
            new Word("dark slate gray"),
            new Word("dark spring green"),
            new Word("dark tan"),
            new Word("dark tangerine"),
            new Word("dark taupe"),
            new Word("dark terra cotta"),
            new Word("dark turquoise"),
            new Word("dark vanilla"),
            new Word("dark violet"),
            new Word("dark yellow"),
            new Word("dartmouth green"),
            new Word("davy's grey"),
            new Word("debian red"),
            new Word("deep amethyst"),
            new Word("deep aquamarine"),
            new Word("deep carmine"),
            new Word("deep carmine pink"),
            new Word("deep carrot orange"),
            new Word("deep cerise"),
            new Word("deep champagne"),
            new Word("deep chestnut"),
            new Word("deep coffee"),
            new Word("deep fuchsia"),
            new Word("deep green"),
            new Word("deep green-cyan turquoise"),
            new Word("deep jungle green"),
            new Word("deep koamaru"),
            new Word("deep lemon"),
            new Word("deep lilac"),
            new Word("deep magenta"),
            new Word("deep maroon"),
            new Word("deep mauve"),
            new Word("deep moss green"),
            new Word("deep peach"),
            new Word("deep pink"),
            new Word("deep puce"),
            new Word("deep red"),
            new Word("deep ruby"),
            new Word("deep saffron"),
            new Word("deep sky blue"),
            new Word("deep space sparkle"),
            new Word("deep spring bud"),
            new Word("deep taupe"),
            new Word("deep tuscan red"),
            new Word("deep violet"),
            new Word("denim blue"),
            new Word("desert sand"),
            new Word("diamond"),
            new Word("dim gray"),
            new Word("dirty brown"),
            new Word("dirty white"),
            new Word("dodger blue"),
            new Word("dodie yellow"),
            new Word("dogwood rose"),
            new Word("dolphin gray"),
            new Word("donkey brown"),
            new Word("drab"),
            new Word("duke blue"),
            new Word("dust storm"),
            new Word("dutch white"),
            new Word("earth yellow"),
            new Word("ebony"),
            new Word("ecru"),
            new Word("eerie black"),
            new Word("eggplant"),
            new Word("eggshell"),
            new Word("egyptian blue"),
            new Word("electric blue"),
            new Word("electric crimson"),
            new Word("electric cyan"),
            new Word("electric green"),
            new Word("electric indigo"),
            new Word("electric lavender"),
            new Word("electric lime"),
            new Word("electric purple"),
            new Word("electric ultramarine"),
            new Word("electric violet"),
            new Word("electric yellow"),
            new Word("emerald"),
            new Word("emerald green"),
            new Word("english green"),
            new Word("english lavender"),
            new Word("english red"),
            new Word("english vermillion"),
            new Word("english violet"),
            new Word("eton blue"),
            new Word("eucalyptus"),
            new Word("fallow"),
            new Word("falu red"),
            new Word("fandango pink"),
            new Word("fashion fuchsia"),
            new Word("feldgrau"),
            new Word("feldspar"),
            new Word("fern green"),
            new Word("ferrari red"),
            new Word("field drab"),
            new Word("fiery rose"),
            new Word("firebrick"),
            new Word("fire engine red"),
            new Word("fire opal"),
            new Word("flame"),
            new Word("flamingo pink"),
            new Word("flavescent"),
            new Word("flax"),
            new Word("flesh"),
            new Word("flirt"),
            new Word("floral white"),
            new Word("fluorescent orange"),
            new Word("fluorescent pink"),
            new Word("fluorescent yellow"),
            new Word("folly"),
            new Word("forest green"),
            new Word("french beige"),
            new Word("french bistre"),
            new Word("french blue"),
            new Word("french fuchsia"),
            new Word("french lilac"),
            new Word("french lime"),
            new Word("french mauve"),
            new Word("french pink"),
            new Word("french plum"),
            new Word("french puce"),
            new Word("french raspberry"),
            new Word("french rose"),
            new Word("french sky blue"),
            new Word("french violet"),
            new Word("french wine"),
            new Word("fresh air"),
            new Word("frostbite"),
            new Word("fuchsia"),
            new Word("fuchsia pink"),
            new Word("fuchsia purple"),
            new Word("fuchsia rose"),
            new Word("gamboge"),
            new Word("gamboge orange-brown"),
            new Word("granet"),
            new Word("generic viridian"),
            new Word("ghost white"),
            new Word("giants orange"),
            new Word("ginger"),
            new Word("glossy grape"),
            new Word("gold"),
            new Word("gold fusion"),
            new Word("gold foil"),
            new Word("golden brown"),
            new Word("golden poppy"),
            new Word("golden yellow"),
            new Word("goldenrod"),
            new Word("granite gray"),
            new Word("granny smith apple"),
            new Word("grape"),
            new Word("gray"),
            new Word("gray-asparagus"),
            new Word("gray-blue"),
            new Word("green"),
            new Word("green-blue"),
            new Word("green-cyan"),
            new Word("green lizard"),
            new Word("green sheen"),
            new Word("green-yellow"),
            new Word("guppie green"),
            new Word("gunmetal"),
            new Word("halloween orange"),
            new Word("han blue"),
            new Word("han purple"),
            new Word("hansa yellow"),
            new Word("harlequin green"),
            new Word("harvard crimson"),
            new Word("harvest gold"),
            new Word("heart gold"),
            new Word("heidelberg red"),
            new Word("heliotrope gray"),
            new Word("heliotrope magenta"),
            new Word("hollywood cerise"),
            new Word("honeydew"),
            new Word("honolulu blue"),
            new Word("hooker's green"),
            new Word("hot magenta"),
            new Word("hot pink"),
            new Word("hunter green"),
            new Word("iceberg"),
            new Word("icterine"),
            new Word("iguana green"),
            new Word("illuminating emerald"),
            new Word("imperial blue"),
            new Word("imperial purple"),
            new Word("imperial red"),
            new Word("india green"),
            new Word("indian red"),
            new Word("indian yellow"),
            new Word("indigo"),
            new Word("infra red"),
            new Word("interdimensional blue"),
            new Word("international klein blue"),
            new Word("international orange"),
            new Word("iris"),
            new Word("isabelline"),
            new Word("islamic green"),
            new Word("italian sky blue"),
            new Word("ivory"),
            new Word("jade"),
            new Word("japanese carmine"),
            new Word("japanese indigo"),
            new Word("japanese laurel"),
            new Word("japanese violet"),
            new Word("jasmine"),
            new Word("jasper orange"),
            new Word("jelly bean blue"),
            new Word("jet"),
            new Word("jonquil"),
            new Word("jordy blue"),
            new Word("jungle green"),
            new Word("kelly green"),
            new Word("kenyan copper"),
            new Word("keppel"),
            new Word("key lime"),
            new Word("khaki"),
            new Word("kiwi"),
            new Word("kombu green"),
            new Word("la salle green"),
            new Word("languid lavender"),
            new Word("lapis lazuli"),
            new Word("laser lemon"),
            new Word("laurel green"),
            new Word("lava"),
            new Word("lavender"),
            new Word("lavender blue"),
            new Word("lavender blush"),
            new Word("lavender gray"),
            new Word("lavender indigo"),
            new Word("lavender magenta"),
            new Word("lavender mist"),
            new Word("lavender pink"),
            new Word("lavender purple"),
            new Word("lavender rose"),
            new Word("lawn green"),
            new Word("lemon"),
            new Word("lemon chiffon"),
            new Word("lemon curry"),
            new Word("lemon glacier"),
            new Word("lemon lime"),
            new Word("lemon meringue"),
            new Word("lemon yellow"),
            new Word("lenurple"),
            new Word("liberty"),
            new Word("licorice"),
            new Word("light apricot"),
            new Word("light blue"),
            new Word("light brilliant red"),
            new Word("light brown"),
            new Word("light carmine pink"),
            new Word("light cobalt blue"),
            new Word("light coral"),
            new Word("light cornflower blue"),
            new Word("light crimson"),
            new Word("light cyan"),
            new Word("light deep pink"),
            new Word("light french beige"),
            new Word("light fuchsia pink"),
            new Word("light gold"),
            new Word("light goldenrod yellow"),
            new Word("light gray"),
            new Word("light grayish magenta"),
            new Word("light green"),
            new Word("light hot pink"),
            new Word("light khaki"),
            new Word("light medium orchid"),
            new Word("light moss green"),
            new Word("light orange"),
            new Word("light orchid"),
            new Word("light pastel purple"),
            new Word("light periwinkle"),
            new Word("light pink"),
            new Word("light red"),
            new Word("light red ochre"),
            new Word("light salmon"),
            new Word("light salmon pink"),
            new Word("light sea green"),
            new Word("light silver"),
            new Word("light sky blue"),
            new Word("light slate gray"),
            new Word("light steel blue"),
            new Word("light taupe"),
            new Word("light thulian pink"),
            new Word("light yellow"),
            new Word("lilac"),
            new Word("lilac luster"),
            new Word("lime"),
            new Word("lime green"),
            new Word("limerick"),
            new Word("lincoln green"),
            new Word("linen"),
            new Word("lion"),
            new Word("liseran purple"),
            new Word("little boy blue"),
            new Word("little girl pink"),
            new Word("maastricht blue"),
            new Word("madder lake"),
            new Word("magenta"),
            new Word("magenta haze"),
            new Word("magenta-pink"),
            new Word("magic mint"),
            new Word("magnolia"),
            new Word("mahogany"),
            new Word("maize"),
            new Word("majorelle blue"),
            new Word("malachite"),
            new Word("manatee gray"),
            new Word("mandarin"),
            new Word("mango"),
            new Word("mango green"),
            new Word("mango yellow"),
            new Word("marigold"),
            new Word("maroon"),
            new Word("mauve"),
            new Word("mauve taupe"),
            new Word("mauvelous"),
            new Word("maximum blue"),
            new Word("maximum blue green"),
            new Word("maximum blue purple"),
            new Word("maximum green"),
            new Word("maximum green yellow"),
            new Word("maximum purple"),
            new Word("maximum red"),
            new Word("maximum red purple"),
            new Word("maximum yellow"),
            new Word("maximum yellow red"),
            new Word("may green"),
            new Word("maya blue"),
            new Word("meat brown"),
            new Word("medium aquamarine"),
            new Word("medium blue"),
            new Word("medium candy apple red"),
            new Word("medium carmine"),
            new Word("medium champagne"),
            new Word("medium electric blue"),
            new Word("medium jungle green"),
            new Word("medium lavender magenta"),
            new Word("medium orchid"),
            new Word("medium persian blue"),
            new Word("medium purple"),
            new Word("medium red-violet"),
            new Word("medium ruby"),
            new Word("medium sea green"),
            new Word("medium sky blue"),
            new Word("medium slate blue"),
            new Word("medium spring bud"),
            new Word("medium spring green"),
            new Word("medium taupe"),
            new Word("medium turquoise"),
            new Word("medium tuscan red"),
            new Word("medium vermilion"),
            new Word("medium violet-red"),
            new Word("mellow apricot"),
            new Word("mellow yellow"),
            new Word("melon"),
            new Word("menthol"),
            new Word("metallic blue"),
            new Word("metallic bronze"),
            new Word("metallic brown"),
            new Word("metallic gold"),
            new Word("metallic green"),
            new Word("metallic orange"),
            new Word("metallic pink"),
            new Word("metallic red"),
            new Word("metallic seaweed"),
            new Word("metallic silver"),
            new Word("metallic sunburst"),
            new Word("metallic violet"),
            new Word("metallic yellow"),
            new Word("mexican pink"),
            new Word("middle blue"),
            new Word("middle blue green"),
            new Word("middle blue purple"),
            new Word("middle grey"),
            new Word("middle green"),
            new Word("middle green yellow"),
            new Word("middle purple"),
            new Word("middle red"),
            new Word("middle red purple"),
            new Word("middle yellow"),
            new Word("middle yellow red"),
            new Word("midnight"),
            new Word("midnight blue"),
            new Word("midnight green"),
            new Word("mikado yellow"),
            new Word("milk chocolate"),
            new Word("mimi pink"),
            new Word("mindaro"),
            new Word("minion yellow"),
            new Word("mint"),
            new Word("mint cream"),
            new Word("mint green"),
            new Word("misty moss"),
            new Word("misty rose"),
            new Word("moccasin"),
            new Word("mode beige"),
            new Word("moonstone blue"),
            new Word("mordant red"),
            new Word("morning blue"),
            new Word("moss green"),
            new Word("mountain meadow"),
            new Word("mountbatten pink"),
            new Word("mud"),
            new Word("mughal green"),
            new Word("mulberry"),
            new Word("mustard"),
            new Word("mustard brown"),
            new Word("mustard green"),
            new Word("mustard yellow"),
            new Word("myrtle green"),
            new Word("mystic maroon"),
            new Word("mystic red"),
            new Word("nadeshiko pink"),
            new Word("napier green"),
            new Word("naples yellow"),
            new Word("navajo white"),
            new Word("navy"),
            new Word("navy blue"),
            new Word("navy purple"),
            new Word("neon blue"),
            new Word("neon brown"),
            new Word("neon carrot"),
            new Word("neon cyan"),
            new Word("neon fuchsia"),
            new Word("neon gold"),
            new Word("neon gray"),
            new Word("neon green"),
            new Word("neon orange"),
            new Word("neon pink"),
            new Word("neon purple"),
            new Word("neon red"),
            new Word("neon scarlet"),
            new Word("neon silver"),
            new Word("neon tangerine"),
            new Word("neon yellow"),
            new Word("new york pink"),
            new Word("nickel"),
            new Word("non-photo blue"),
            new Word("north texas green"),
            new Word("ocean blue"),
            new Word("ocean boat blue"),
            new Word("ocean green"),
            new Word("ochre"),
            new Word("office green"),
            new Word("old burgundy"),
            new Word("old gold"),
            new Word("old heliotrope"),
            new Word("old lace"),
            new Word("old lavender"),
            new Word("old mauve"),
            new Word("old moss green"),
            new Word("old rose"),
            new Word("old silver"),
            new Word("olive"),
            new Word("olive drab"),
            new Word("olivine"),
            new Word("onyx"),
            new Word("opal"),
            new Word("opera mauve"),
            new Word("orange"),
            new Word("orange peel"),
            new Word("orange-red"),
            new Word("orange soda"),
            new Word("orange-yellow"),
            new Word("orchid"),
            new Word("orchid pink"),
            new Word("orioles orange"),
            new Word("otter brown"),
            new Word("outer space"),
            new Word("outrageous orange"),
            new Word("oxford blue"),
            new Word("oxley"),
            new Word("pacific blue"),
            new Word("pakistan green"),
            new Word("palatinate blue"),
            new Word("palatinate purple"),
            new Word("pale aqua"),
            new Word("pale blue"),
            new Word("pale brown"),
            new Word("pale carmine"),
            new Word("pale cerulean"),
            new Word("pale chestnut"),
            new Word("pale copper"),
            new Word("pale cornflower blue"),
            new Word("pale cyan"),
            new Word("pale gold"),
            new Word("pale goldenrod"),
            new Word("pale green"),
            new Word("pale lavender"),
            new Word("pale magenta"),
            new Word("pale magenta-pink"),
            new Word("pale pink"),
            new Word("pale plum"),
            new Word("pale red-violet"),
            new Word("pale robin egg blue"),
            new Word("pale silver"),
            new Word("pale spring bud"),
            new Word("pale taupe"),
            new Word("pale turquoise"),
            new Word("pale violet"),
            new Word("pale violet-red"),
            new Word("palm leaf"),
            new Word("pansy purple"),
            new Word("paolo veronese green"),
            new Word("papaya whip"),
            new Word("paradise pink"),
            new Word("paris green"),
            new Word("parrot pink"),
            new Word("pastel blue"),
            new Word("pastel brown"),
            new Word("pastel gray"),
            new Word("pastel green"),
            new Word("pastel magenta"),
            new Word("pastel orange"),
            new Word("pastel pink"),
            new Word("pastel purple"),
            new Word("pastel red"),
            new Word("pastel violet"),
            new Word("pastel yellow"),
            new Word("patriarch"),
            new Word("payne's grey"),
            new Word("peach"),
            new Word("peach-orange"),
            new Word("peach puff"),
            new Word("peach-yellow"),
            new Word("pear"),
            new Word("pearl"),
            new Word("pearl aqua"),
            new Word("pearly purple"),
            new Word("peridot"),
            new Word("periwinkle"),
            new Word("permanent geranium lake"),
            new Word("persian blue"),
            new Word("persian green"),
            new Word("persian indigo"),
            new Word("persian orange"),
            new Word("persian pink"),
            new Word("persian plum"),
            new Word("persian red"),
            new Word("persian rose"),
            new Word("persimmon"),
            new Word("peru"),
            new Word("pewter blue"),
            new Word("philippine blue"),
            new Word("philippine brown"),
            new Word("philippine gold"),
            new Word("philippine golden yellow"),
            new Word("philippine gray"),
            new Word("philippine green"),
            new Word("philippine orange"),
            new Word("philippine pink"),
            new Word("philippine red"),
            new Word("philippine silver"),
            new Word("philippine violet"),
            new Word("philippine yellow"),
            new Word("phthalo blue"),
            new Word("phthalo green"),
            new Word("picton blue"),
            new Word("pictorial carmine"),
            new Word("piggy pink"),
            new Word("pine green"),
            new Word("pine tree"),
            new Word("pineapple"),
            new Word("pink"),
            new Word("pink flamingo"),
            new Word("pink lace"),
            new Word("pink lavender"),
            new Word("pink-orange"),
            new Word("pink pearl"),
            new Word("pink raspberry"),
            new Word("pink sherbet"),
            new Word("pistachio"),
            new Word("pixie powder"),
            new Word("platinum"),
            new Word("plum"),
            new Word("plump purple"),
            new Word("police blue"),
            new Word("polished pine"),
            new Word("pomp and power"),
            new Word("popstar"),
            new Word("portland orange"),
            new Word("powder blue"),
            new Word("princess perfume"),
            new Word("princeton orange"),
            new Word("prune"),
            new Word("prussian blue"),
            new Word("psychedelic purple"),
            new Word("puce"),
            new Word("puce red"),
            new Word("pullman brown"),
            new Word("pullman green"),
            new Word("pumpkin"),
            new Word("purple"),
            new Word("purple heart"),
            new Word("purple mountain majesty"),
            new Word("purple navy"),
            new Word("purple pizzazz"),
            new Word("purple plum"),
            new Word("purple taupe"),
            new Word("purpureus"),
            new Word("quartz"),
            new Word("queen blue"),
            new Word("queen pink"),
            new Word("quick silver"),
            new Word("quinacridone magenta"),
            new Word("rackley"),
            new Word("radical red"),
            new Word("raisin black"),
            new Word("raspberry"),
            new Word("raspberry glace"),
            new Word("raspberry pink"),
            new Word("raspberry rose"),
            new Word("raw sienna"),
            new Word("raw umber"),
            new Word("razzle dazzle rose"),
            new Word("razzmic berry"),
            new Word("rebecca purple"),
            new Word("red"),
            new Word("red-brown"),
            new Word("red devil"),
            new Word("red-orange"),
            new Word("red-purple"),
            new Word("red salsa"),
            new Word("red-violet"),
            new Word("redwood"),
            new Word("regalia"),
            new Word("registration black"),
            new Word("resolution blue"),
            new Word("rhythm"),
            new Word("rich black"),
            new Word("rich brilliant lavender"),
            new Word("rich carmine"),
            new Word("rich electric blue"),
            new Word("rich lavender"),
            new Word("rich lilac"),
            new Word("rich maroon"),
            new Word("rifle green"),
            new Word("roast coffee"),
            new Word("robin egg blue"),
            new Word("rocket metallic"),
            new Word("roman silver"),
            new Word("root beer"),
            new Word("rose"),
            new Word("rose bonbon"),
            new Word("rose dust"),
            new Word("rose ebony"),
            new Word("rose garnet"),
            new Word("rose gold"),
            new Word("rose madder"),
            new Word("rose pink"),
            new Word("rose quartz"),
            new Word("rose quartz pink"),
            new Word("rose red"),
            new Word("rose taupe"),
            new Word("rose vale"),
            new Word("rosewood"),
            new Word("rosso corsa"),
            new Word("rosy brown"),
            new Word("royal azure"),
            new Word("royal blue"),
            new Word("royal blue"),
            new Word("royal brown"),
            new Word("royal fuchsia"),
            new Word("royal green"),
            new Word("royal orange"),
            new Word("royal pink"),
            new Word("royal red"),
            new Word("royal red"),
            new Word("royal purple"),
            new Word("royal yellow"),
            new Word("rubine red"),
            new Word("ruby"),
            new Word("ruby red"),
            new Word("ruddy brown"),
            new Word("ruddy pink"),
            new Word("russet"),
            new Word("russian green"),
            new Word("russian violet"),
            new Word("rust"),
            new Word("rusty red"),
            new Word("sacramento state green"),
            new Word("saddle brown"),
            new Word("safety orange"),
            new Word("safety yellow"),
            new Word("saffron"),
            new Word("sage"),
            new Word("st. patrick's blue"),
            new Word("salmon"),
            new Word("salmon pink"),
            new Word("sandy brown"),
            new Word("sandy tan"),
            new Word("sandy taupe"),
            new Word("sangria"),
            new Word("sap green"),
            new Word("sapphire blue"),
            new Word("satin sheen gold"),
            new Word("scarlet"),
            new Word("schauss pink"),
            new Word("school bus yellow"),
            new Word("screamin' green"),
            new Word("sea blue"),
            new Word("sea foam green"),
            new Word("sea green"),
            new Word("seal brown"),
            new Word("seashell"),
            new Word("selective yellow"),
            new Word("sepia"),
            new Word("shadow"),
            new Word("shadow blue"),
            new Word("shampoo"),
            new Word("shamrock green"),
            new Word("sheen green"),
            new Word("shimmering blush"),
            new Word("shiny shamrock"),
            new Word("shocking pink"),
            new Word("sienna"),
            new Word("silver"),
            new Word("silver chalice"),
            new Word("silver foil"),
            new Word("silver lake blue"),
            new Word("silver pink"),
            new Word("silver sand"),
            new Word("sinopia"),
            new Word("sizzling red"),
            new Word("sizzling sunrise"),
            new Word("skobeloff"),
            new Word("sky blue"),
            new Word("sky magenta"),
            new Word("slate blue"),
            new Word("slate gray"),
            new Word("slimy green"),
            new Word("smashed pumpkin"),
            new Word("smitten"),
            new Word("smoke"),
            new Word("smokey topaz"),
            new Word("smoky black"),
            new Word("smoky topaz"),
            new Word("snow"),
            new Word("soldier green"),
            new Word("solid pink"),
            new Word("sonic silver"),
            new Word("spartan crimson"),
            new Word("space cadet"),
            new Word("spanish bistre"),
            new Word("spanish blue"),
            new Word("spanish carmine"),
            new Word("spanish crimson"),
            new Word("spanish gray"),
            new Word("spanish green"),
            new Word("spanish orange"),
            new Word("spanish pink"),
            new Word("spanish purple"),
            new Word("spanish red"),
            new Word("spanish sky blue"),
            new Word("spanish violet"),
            new Word("spanish viridian"),
            new Word("spanish yellow"),
            new Word("spicy mix"),
            new Word("spring bud"),
            new Word("spring frost"),
            new Word("spring green"),
            new Word("star command blue"),
            new Word("steel blue"),
            new Word("steel pink"),
            new Word("steel teal"),
            new Word("stil de grain yellow"),
            new Word("stormcloud"),
            new Word("straw"),
            new Word("strawberry"),
            new Word("sugar plum"),
            new Word("sunburnt cyclops"),
            new Word("sunglow"),
            new Word("sunny"),
            new Word("sunray"),
            new Word("sunset"),
            new Word("sunset orange"),
            new Word("super pink"),
            new Word("sweet brown"),
            new Word("tan"),
            new Word("tangelo"),
            new Word("tangerine"),
            new Word("tangerine yellow"),
            new Word("tango pink"),
            new Word("tart orange"),
            new Word("taupe"),
            new Word("taupe gray"),
            new Word("tea green"),
            new Word("tea rose"),
            new Word("teal"),
            new Word("teal blue"),
            new Word("teal deer"),
            new Word("teal green"),
            new Word("telemagenta"),
            new Word("temptress"),
            new Word("terra cotta"),
            new Word("thistle"),
            new Word("thulian pink"),
            new Word("tickle me pink"),
            new Word("tiffany blue"),
            new Word("tiger's eye"),
            new Word("timberwolf"),
            new Word("titanium"),
            new Word("titanium yellow"),
            new Word("tomato"),
            new Word("toolbox"),
            new Word("topaz"),
            new Word("tractor red"),
            new Word("trolley grey"),
            new Word("tropical rain forest"),
            new Word("tropical violet"),
            new Word("true blue"),
            new Word("tufts blue"),
            new Word("tulip"),
            new Word("tumbleweed"),
            new Word("turkish rose"),
            new Word("turquoise"),
            new Word("turquoise blue"),
            new Word("turquoise green"),
            new Word("turquoise surf"),
            new Word("turtle green"),
            new Word("tuscan"),
            new Word("tuscan brown"),
            new Word("tuscan red"),
            new Word("tuscan tan"),
            new Word("tuscany"),
            new Word("twilight lavender"),
            new Word("tyrian purple"),
            new Word("ufo green"),
            new Word("ultramarine"),
            new Word("ultramarine blue"),
            new Word("ultra pink"),
            new Word("ultra red"),
            new Word("umber"),
            new Word("unbleached silk"),
            new Word("united nations blue"),
            new Word("unmellow yellow"),
            new Word("ups brown"),
            new Word("upsdell red"),
            new Word("urobilin"),
            new Word("utah crimson"),
            new Word("vampire black"),
            new Word("van dyke brown"),
            new Word("vanilla"),
            new Word("vanilla ice"),
            new Word("vegas gold"),
            new Word("venetian red"),
            new Word("verdigris"),
            new Word("vermilion"),
            new Word("vermilion"),
            new Word("veronica"),
            new Word("verse green"),
            new Word("very light azure"),
            new Word("very light blue"),
            new Word("very light malachite green"),
            new Word("very light tangelo"),
            new Word("very pale orange"),
            new Word("very pale yellow"),
            new Word("violet"),
            new Word("violet-blue"),
            new Word("violet-red"),
            new Word("violin brown"),
            new Word("viridian"),
            new Word("viridian green"),
            new Word("vista blue"),
            new Word("vivid amber"),
            new Word("vivid auburn"),
            new Word("vivid burgundy"),
            new Word("vivid cerise"),
            new Word("vivid cerulean"),
            new Word("vivid crimson"),
            new Word("vivid gamboge"),
            new Word("vivid lime green"),
            new Word("vivid malachite"),
            new Word("vivid mulberry"),
            new Word("vivid orange"),
            new Word("vivid orange peel"),
            new Word("vivid orchid"),
            new Word("vivid raspberry"),
            new Word("vivid red"),
            new Word("vivid red-tangelo"),
            new Word("vivid sky blue"),
            new Word("vivid tangelo"),
            new Word("vivid tangerine"),
            new Word("vivid vermilion"),
            new Word("vivid violet"),
            new Word("vivid yellow"),
            new Word("wageningen green"),
            new Word("warm black"),
            new Word("watermelon"),
            new Word("watermelon red"),
            new Word("waterspout"),
            new Word("weldon blue"),
            new Word("wenge"),
            new Word("wheat"),
            new Word("white"),
            new Word("white chocolate"),
            new Word("white coffee"),
            new Word("white smoke"),
            new Word("wild blue yonder"),
            new Word("wild orchid"),
            new Word("wild strawberry"),
            new Word("wild watermelon"),
            new Word("willpower orange"),
            new Word("windsor tan"),
            new Word("wine"),
            new Word("wine red"),
            new Word("winter sky"),
            new Word("wintergreen dream"),
            new Word("wisteria"),
            new Word("wood brown"),
            new Word("xanadu"),
            new Word("yale blue"),
            new Word("yankees blue"),
            new Word("yellow"),
            new Word("yellow-green"),
            new Word("yellow orange"),
            new Word("yellow rose"),
            new Word("yellow sunshine"),
            new Word("zinnwaldite brown"),

        });

        public static Choice MoodAdjective = new Choice(new List<IGenerate>
        {
            new Word("mad"),
            new Word("sad"),
            new Word("blissful"),
            new Word("furious"),
            new Word("cheerful"),
            new Word("crying"),
            new Word("funny"),
            new Word("happy"),
            new Word("laughing"),
            new Word("screaming"),
            new Word("tragic"),
            new Word("melancholy"),
            new Word("wistful"),

        });

        public static Choice Season = new Choice(new List<IGenerate>
        {
            new Word("April"),
            new Word("August"),
            new Word("Autumn"),
            new Word("December"),
            new Word("Fall"),
            new Word("February"),
            new Word("Harvest"),
            new Word("January"),
            new Word("July"),
            new Word("June"),
            new Word("March"),
            new Word("May"),
            new Word("Midsummer"),
            new Word("November"),
            new Word("October"),
            new Word("September"),
            new Word("Spring"),
            new Word("Summer"),
            new Word("Winter"),
            new Word("Wintertide"),

        });

        public static Choice SizeAdjective = new Choice(new List<IGenerate>
        {
            new Word("big"),
            new Word("fat"),
            new Word("huge"),
            new Word("small"),
            new Word("thin"),
            new Word("vast"),
            new Word("little"),
            new Word("tiny"),
            new Word("enormous"),
            new Word("tremendous"),

        });

        public static Choice AgeAdjective = new Choice(new List<IGenerate>
        {
            new Word("old"),
            new Word("sick"),
            new Word("young"),
            new Word("aged"),
            new Word("ailing"),
            new Word("fledgling"),
            new Word("infant"),
            new Word("newborn"),
            new Word("older"),
            new Word("younger"),
            new Word("mature"),
            new Word("pubescent"),

        });

        public static Choice Adverb = new Choice(new List<IGenerate>
        {
            new Word("bleakly"),
            new Word("blindly"),
            new Word("gladly"),
            new Word("lightly"),
            new Word("quickly"),
            new Word("sadly"),
            new Word("slowly"),
            new Word("smoothly"),
            new Word("strangely"),
            new Word("angrily"),
            new Word("boastfully"),
            new Word("carefully"),
            new Word("daintily"),
            new Word("gracefully"),
            new Word("happily"),
            new Word("joyfully"),
            new Word("knowingly"),
            new Word("lazily"),
            new Word("playfully"),
            new Word("quietly"),
            new Word("woefully"),
            new Word("defiantly"),
            new Word("ferociously"),
            new Word("furiously"),

        });

        public static Choice At = new Choice(new List<IGenerate>
        {
            new Word("at")
        });

        public static Choice In = new Choice(new List<IGenerate>
        {
            new Word("in")
        });

        public static Choice AtIn = At + In;

        public static Choice From = new Choice(new List<IGenerate>
        {
            new Word("from")
        });

        public static Choice To = new Choice(new List<IGenerate>
        {
            new Word("to"),
            new Word("towards")
        });

        public static Choice Direction = To + From;

    }
}
